apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:  
  name: K8sDeveloper
rules:
- apiGroups: [""] 
  resources: 
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: K8sDeveloperBinding
  namespace: default
subjects:
- kind: Group
  name: f0ae16f0-e521-4b30-b097-293adeba8f9e
  apiGroup: rbac.authorization.k8s.io
roleRef:  
  kind: Role 
  name: K8sDeveloper
  apiGroup: rbac.authorization.k8s.io
---